version: "3.8"

services:
    api-v2:
        container_name: social-coder-apiv2
        image: social-code-apiv2
        hostname: social-coder-api-v2
        environment:
            - ReportPath=/socialcoder/Data/Reports
        volumes:
            - ./appsettings.json:/app/appsettings.json
            - /socialcoder/Data:/app/Data:rw
            - "/var/run/docker.sock:/var/run/docker.sock:Z"