namespace Core.Storage;

/// <summary>
/// Assists with figuring out paths on any OS.
/// </summary>
public class AppStorage : IStorageHandler
{
    /// <summary>
    /// Basic folder to store application-based data
    /// </summary>
    public static string AppDataPath => Path.Join(AppDomain.CurrentDomain.BaseDirectory, "Data");
    
    /// <summary>
    /// Stores profiling configuration files used for static code analysis and such.
    /// </summary>
    public static string ToolsProfilePath => Path.Join(AppDataPath, "Profiles");
    
    public static string ScriptsPath => PathFromData("Scripts");
    
    /// <summary>
    /// Reports generated from tests and such go here
    /// </summary>
    public static string ReportsPath => Path.Join(AppDataPath, "Reports");
    
    /// <summary>
    /// Any config files needed go here
    /// </summary>
    public static string ConfigsPath => Path.Join(AppDataPath, "Configs");
    
    /// <summary>
    /// Files that are not used long-term but generated by the application shall use this location.
    /// If cleanup fails for whatever reason, it is safe to assume this folder can be wiped
    /// </summary>
    public static string TemporaryFileStorage => Path.Join(AppDataPath, "Temp");
    public static string Snippets => Path.Join(AppDataPath, "Snippets");
    public static string GeneratedReports => Path.Join(AppDomain.CurrentDomain.BaseDirectory, "web", "reports");

    /// <summary>
    /// Get Path from <see cref="AppDomain.CurrentDomain.BaseDirectory"/>
    /// </summary>
    /// <param name="folders"></param>
    /// <returns></returns>
    public static string PathFromDomain(params string[] folders)
    {
        var list = folders.ToList();
        list.Insert(0, AppDomain.CurrentDomain.BaseDirectory);
        return Path.Join(list.ToArray());
    }
    
    /// <summary>
    /// Get path from <see cref="AppDomain.CurrentDomain.BaseDirectory"/>/Data
    /// </summary>
    /// <param name="folders"></param>
    /// <returns></returns>
    public static string PathFromData(params string[] folders)
    {
        var list = folders.ToList();
        list.Insert(0, AppDataPath);
        return Path.Join(list.ToArray());
    }
    
    public static void InitializeStorage()
    {
        string[] paths =
        {
            AppDataPath, ToolsProfilePath, ScriptsPath, ConfigsPath, TemporaryFileStorage, Snippets, GeneratedReports
        };
        
        foreach(var path in paths)
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);
    }
}